apiVersion : apps/v1
kind: Deployment
metadata:
  name: forimages 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forimages
  template:
    metadata:
      labels:
        app: forimages 
    spec:
      containers:
        - name: forimages 
          image: aksdevops2.azurecr.io/forimages
          ports:
          - containerPort: 80